apiVersion: v1
kind: Service
metadata:
  name: xpilot-bot-staging-svc
  namespace: xpilot-staging
spec:
  type: ClusterIP
  selector:
    app: xpilot-bot-staging
  ports:
    - targetPort: 3978
      port: 80