apiVersion: v1
kind: Secret
metadata:
  name: xpilot-bot-secret
  namespace: ai
type: Opaque
stringData:
  MICROSOFT_APP_ID: 2f1bd833-b2e7-48be-9075-b13623cc9165
  MICROSOFT_APP_PASSWORD: EjJ8Q~JAYn-b063yVYYKTbl34t2FZko9saB.hagx
  MICROSOFT_APP_TENANT_ID: 2780a32d-11ce-4c57-bad5-ce0cffc115a3
  LANGFLOW_URL: https://st-langflow.smart.com.kh
  LANGFLOW_API_KEY: sk-OOmJoYBQgKGUe9QfenxJqWMbERjGD5akzFGiW4MZFTY
  LANGFLOW_CHAT_FLOW_ID: 22da4d91-0d3a-4d11-a35f-45a63baf6e8d/folder/2b8c315f-af55-4ba3-89e8-bb2c7a6aeb7b
  LANGFLOW_REQUIREMENT_FLOW_ID: 6c1ade04-bfb5-4edc-8738-a40cf1b4c93d/folder/2b8c315f-af55-4ba3-89e8-bb2c7a6aeb7b
  PORT: "3978"
